# Generated by Django 3.2.6 on 2022-04-12 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rossoftai.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('algorithm', models.CharField(choices=[('apriori', 'Apriori'), ('metrics', 'Metrics'), ('clusteringH', 'ClusteringH'), ('clusteringP', 'ClusteringP')], max_length=12)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.FileField(upload_to=rossoftai.models.user_directory_report_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.FileField(upload_to=rossoftai.models.user_directory_data_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
