# Generated by Django 3.2.6 on 2022-04-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rossoftai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='data',
            new_name='file',
        ),
    ]
